library(ncdf4)
library(lubridate)

load_ssi <- function(option = c("synthetic", "true", "simulation","toy","csim"), 
                     synthetic.range = c(ymd(20180314) - ymd(18491230) + 1, ymd(20230129) - ymd(18491230) + 1),
                     missing.option = c("0", "true", "synthetic"),
                     mask = NULL,
                     simu.function = NULL, ...) {
  # Input
  # - missing.mask: the mask matrix indicating the missingness, if missing.option == "synthetic"
  # Synthetic ssi -------------------------
  if (option == "synthetic") {
    nc_data <- nc_open("./data/ssi_synthetic_interpolated.nc")
    ssi_interpolated <- ncvar_get(nc_data, "ssi_interpolated")
    time <- ncvar_get(nc_data, "time")
    wvl <- ncvar_get(nc_data, "wavelength")
    t <- (time + 1.5)*24*60*60 + ymd_hm("1849-12-30 00:00")
    t <- ymd(t)
    t <- as.character(t)
    start <- synthetic.range[1]
    end <- synthetic.range[2]
    xt <- ssi_interpolated[ ,start:end] # interpolated data
    colnames(xt) <- t[start:end]
    rownames(xt) <- wvl
    if (missing.option == "true") {
      x <- xt
      nc_data <- nc_open("./data/TSIS-1_ssi_tsi_20180314_20230129.nc")
      ssi <- ncvar_get(nc_data, "ssi")
      mask <- is.na(ssi)
      x[mask] <- NA
    } else if (missing.option == "0") {
      return(list(xt = xt))
    } else {
      x <- xt
      x[mask] <- NA
    }
    return(list(xt = xt, x=x))
  }
  
  # Observed ssi (TSIS) -----------------------
  if (option == "true") {
    nc_data <- nc_open("./data/TSIS-1_ssi_tsi_20180314_20230129.nc")
    ssi <- ncvar_get(nc_data, "ssi")
    t <- ncvar_get(nc_data, "date")
    t <- ymd(t)
    t <- as.character(t)
    wvl <- ncvar_get(nc_data, "wvl")
    x <- ssi
    x[which(is.nan(x))] <- NA
    colnames(x) <- t
    rownames(x) <- wvl
    return(list(x =x))
  }
  
  # Simulated data ----------------------------
  if (option == "simulation") {
    args <- list(...)
    xt <- simu_AB(args$Sigma_A, args$gamma, args$tau2, args$sigma2, args$n)
    
    if (missing.option == "true") {
      x <- xt
      nc_data <- nc_open("./data/TSIS-1_ssi_tsi_20180314_20230129.nc")
      ssi <- ncvar_get(nc_data, "ssi")
      mask <- is.na(ssi)
      x[mask] <- NA
    } else if (missing.option == "0") {
      return(list(xt = xt))
    } else {
      x <- xt
      x[mask] <- NA
    }
    return(list(xt = xt, x=x))
  }
  
  # A 100x100 toy example generated by synthetic data and true mask -----------------------------
  if (option == "toy") {
    nc_data <- nc_open("./data/TSIS-1_ssi_tsi_20180314_20230129.nc")
    ssi <- ncvar_get(nc_data, "ssi")
    mask <- is.na(ssi)
    nc_data <- nc_open("./data/ssi_synthetic_interpolated.nc")
    ssi_interpolated <- ncvar_get(nc_data, "ssi_interpolated")
    time <- ncvar_get(nc_data, "time")
    wvl <- ncvar_get(nc_data, "wavelength")
    t <- (time + 1.5)*24*60*60 + ymd_hm("1849-12-30 00:00")
    t <- ymd(t)
    t <- as.character(t)
    start <- synthetic.range[1]
    end <- synthetic.range[2]
    ssi <- ssi_interpolated[ ,start:end] # interpolated data
    xt <- ssi[1:100,1:100]
    colnames(xt) <- t[1:100]
    rownames(xt) <- wvl[1:100]
    x <- xt
    x[mask[1:100,1:100]] <- NA
    
    return(list(xt = xt, x=x))
  }
  if (option == "csim") {
    nc_data <- nc_open("./data/csim_ssi_L3_latest.nc")
    ssi <- ncvar_get(nc_data, "SSI")
    
    time <- ncvar_get(nc_data, "time") # julian date
    t <- time-2458569.5 + ymd("2019-03-27")
    wvl <- ncvar_get(nc_data, "wavelength")
    t <- as.character(t)
    x <- ssi
    colnames(x) <- t
    rownames(x) <- wvl
    return(list(x=x))
  }
}

chunk_mask <- function(m = 2104, n = 1783,
                       option = c("uniform", "alternating.poisson"), 
                       rate1 = 0.046, rate2 = 0.305,
                       ratio = 0.1, 
                       seed = NULL, return = c("mask", "col.ind")) {
  # Generate m x n chunk missingness mask.
  if (!is.null(seed)) {
    set.seed(seed)
  }
  if (option == "alternating.poisson") {
    n.try = ceiling(n / (1/rate1+1/rate2))
    v1 = ceiling(rexp(n.try, rate = rate1))
    v2 = ceiling(rexp(n.try, rate = rate2))
    while (sum(v1+v2)<n) {
      v1 <- c(v1, ceiling(rexp(1, rate = rate1)))
      v2 <- c(v2, ceiling(rexp(1, rate = rate2)))
    }
    while (sum(v1+v2)>n) {
      v1 <- v1[-length(v1)]
      v2 <- v2[-length(v2)]
    }
    ind = unlist(apply(cbind(cumsum(v1+v2)-v2,cumsum(v1+v2)), 1, function(v) (v[1]+1):v[2]))
  } else if (option == "uniform") {
    ind <- sample(n, floor(ratio*n))
  }
  # return 
  if (return == "mask") {
    mask <- matrix(F, nrow = m, ncol = n)
    mask[,ind] <- T
    return(mask)
  } else {
    return(ind)
  }
}

